### ISSUE TITLE
Creative mode gives hypothermia

### ISSUE THREAD

**Issue by Yamza** [Stereowalker/C.O.M.B.A.T.#5]
Entering the world in creative gives hypothermia, which does not end until switching to survival and dying. Biome doesn't seem to matter. I also attempted to disable it via configs but that did not stop it.
https://i.imgur.com/jhTf2SD.png
https://i.imgur.com/A0CXbmg.png

Edit: Also the config does not seem to work at all. Entered this biome and got hypothermia
https://i.imgur.com/Xt0ZFrL.png

Forge: 28.0.49
C.O.M.B.A.T.-1.14.4-0.15.0.jar

**Comment by Stereowalker** [comment]
If you don't disable hypothermia in the serverconfig folder, it will still show in creative. If you want to check whether its enabled or not, press "Y". You should change it in the serverconfig folder [(Mincraft's Location)\saves\(Your World)\serverconfig] for it to have an effect. Its set like that so that you can set individual values for individual worlds
